// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-48391YIC2YkIY9ma5XQc3K306fL0mI',
    appId: '1:922698204191:web:9958a23f219a703fe1c12a',
    messagingSenderId: '922698204191',
    projectId: 'bdciberseguridad',
    authDomain: 'bdciberseguridad.firebaseapp.com',
    storageBucket: 'bdciberseguridad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeaaoMj8ugFbsurk5aHKmWVPqZKLztwQ4',
    appId: '1:922698204191:android:d874b761467dd189e1c12a',
    messagingSenderId: '922698204191',
    projectId: 'bdciberseguridad',
    storageBucket: 'bdciberseguridad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiXy9szR_rhP6scB_XnGCPSDVCvwlwFbg',
    appId: '1:922698204191:ios:589deb1aa9593842e1c12a',
    messagingSenderId: '922698204191',
    projectId: 'bdciberseguridad',
    storageBucket: 'bdciberseguridad.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiXy9szR_rhP6scB_XnGCPSDVCvwlwFbg',
    appId: '1:922698204191:ios:589deb1aa9593842e1c12a',
    messagingSenderId: '922698204191',
    projectId: 'bdciberseguridad',
    storageBucket: 'bdciberseguridad.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp-48391YIC2YkIY9ma5XQc3K306fL0mI',
    appId: '1:922698204191:web:8f18e31e087646eae1c12a',
    messagingSenderId: '922698204191',
    projectId: 'bdciberseguridad',
    authDomain: 'bdciberseguridad.firebaseapp.com',
    storageBucket: 'bdciberseguridad.firebasestorage.app',
  );
}
